export const MONEY_TITLES = {
  '/services/ai-agents': 'AI agent development',
  '/services/ai-agent-security': 'AI agent security',
  '/services/ai-compliance-uae': 'AI compliance in the UAE',
  '/services/agentops': 'AgentOps: monitoring and maintenance',
  '/services/ai-chatbot-development': 'AI chatbot development',
  '/services/ai-agents/voice-agents': 'AI voice agents',
  '/services/arabic-ai': 'Arabic AI services',
  '/services/custom-ai-development': 'Custom AI development',
  '/services/ai-automation': 'AI business automation',
  '/services/ai-agents/dubai': 'AI agents in Dubai',
  '/services/whatsapp-ai-automation': 'WhatsApp AI automation',
  '/services/ai-agents/tools': 'AI agent platforms and tools',
  '/services/ai-strategy': 'AI strategy and readiness',
  '/services/ai-training': 'AI training for teams',
  '/services/ai-integration': 'AI systems integration',
  '/industries': 'AI by industry',
  '/ar/services/ai-agents': 'تطوير وكلاء الذكاء الاصطناعي',
  '/ar/services/arabic-ai/chatbots': 'روبوتات المحادثة العربية',
  '/ar/services/arabic-ai/voice-agents': 'الوكلاء الصوتيون بالعربية',
  '/ar/services/ai-strategy': 'استراتيجية الذكاء الاصطناعي والجاهزية',
  '/ar/services/ai-compliance-uae': 'الامتثال للذكاء الاصطناعي في الإمارات',
  '/ar/services/whatsapp-ai-automation': 'أتمتة واتساب بالذكاء الاصطناعي',
  '/ar/industries': 'الذكاء الاصطناعي حسب القطاع',
};
