// Verified live 2026-09-09. code 200, or 403 = WAF-blocked to bots but reachable
// in a browser, which SOURCE-POLICY.md explicitly permits.
export const SOURCES = {
  pdpl: {
    en: { url: 'https://uaelegislation.gov.ae/en/legislations/2519',
      sentence: "The UAE's [Federal Decree-Law No. 45 of 2021](URL) sets out the lawful bases for processing personal data and the rights a data subject can exercise against a controller." },
    ar: { url: 'https://uaelegislation.gov.ae/ar/legislations/2519',
      sentence: 'يحدد [المرسوم بقانون اتحادي رقم 45 لسنة 2021](URL) الأسس القانونية لمعالجة البيانات الشخصية والحقوق التي يملكها صاحب البيانات في مواجهة جهة التحكم.' },
  },
  pdpl_overview: {
    en: { url: 'https://u.ae/en/about-the-uae/digital-uae/data/data-protection-laws',
      sentence: 'The UAE government publishes a [plain-English summary of the data protection laws](URL) that applies across the federal jurisdiction and the financial free zones.' },
    ar: { url: 'https://u.ae/ar/about-the-uae/digital-uae/data/data-protection-laws',
      sentence: 'تنشر حكومة الإمارات [ملخصاً مبسطاً لقوانين حماية البيانات](URL) السارية على المستوى الاتحادي وداخل المناطق الحرة المالية.' },
  },
  tdra: {
    en: { url: 'https://tdra.gov.ae/en',
      sentence: 'The [Telecommunications and Digital Government Regulatory Authority](URL) is the body that licenses telecom services in the UAE and sets the rules for unsolicited marketing contact.' },
    ar: { url: 'https://tdra.gov.ae/ar',
      sentence: 'إن [هيئة تنظيم الاتصالات والحكومة الرقمية](URL) هي الجهة التي ترخّص خدمات الاتصالات في الإمارات وتضع قواعد التواصل التسويقي غير المرغوب فيه.' },
  },
  dncr: {
    en: { url: 'https://www.moec.gov.ae/en/-/do-not-call-registry',
      sentence: 'The Ministry of Economy and Tourism runs the [Do Not Call Registry](URL), and any outbound campaign has to check it before it dials.' },
    ar: { url: 'https://www.moec.gov.ae/ar/-/do-not-call-registry',
      sentence: 'تدير وزارة الاقتصاد والسياحة [سجل عدم الاتصال](URL)، ويلزم مراجعته قبل أي حملة اتصال صادرة.' },
  },
  moec: {
    en: { url: 'https://www.moec.gov.ae/en/consumer-protection',
      sentence: 'The same ministry sets the [consumer protection rules](URL) that apply to automated sales contact just as they do to a human sales team.' },
    ar: { url: 'https://www.moec.gov.ae/ar/consumer-protection',
      sentence: 'وتضع الوزارة نفسها [قواعد حماية المستهلك](URL) التي تسري على التواصل البيعي الآلي كما تسري على فريق مبيعات بشري.' },
  },
  adgm: {
    en: { url: 'https://www.adgm.com/operating-in-adgm/office-of-data-protection',
      sentence: 'Abu Dhabi Global Market runs its own data protection regime through its [Office of Data Protection](URL), separate from the federal law.' },
    ar: { url: 'https://www.adgm.com/operating-in-adgm/office-of-data-protection',
      sentence: 'يطبّق سوق أبوظبي العالمي نظام حماية بيانات خاصاً به عبر [مكتب حماية البيانات](URL)، منفصلاً عن القانون الاتحادي.' },
  },
  cbuae: {
    en: { url: 'https://rulebook.centralbank.ae/',
      sentence: 'Licensed financial institutions work to the [Central Bank of the UAE rulebook](URL), which covers outsourcing, model risk and how customer data may be handled.' },
    ar: { url: 'https://rulebook.centralbank.ae/',
      sentence: 'تعمل المؤسسات المالية المرخّصة وفق [كتيب قواعد مصرف الإمارات المركزي](URL)، الذي يغطي الاستعانة بمصادر خارجية ومخاطر النماذج وطريقة التعامل مع بيانات العملاء.' },
  },
  mohre: {
    en: { url: 'https://www.mohre.gov.ae/en/laws-and-regulations.aspx',
      sentence: 'The Ministry of Human Resources and Emiratisation publishes the [labour laws and regulations](URL) that any HR automation has to work inside.' },
    ar: { url: 'https://www.mohre.gov.ae/ar/home.aspx',
      sentence: 'تنشر [وزارة الموارد البشرية والتوطين](URL) قوانين العمل واللوائح التي يجب أن تعمل أي أتمتة للموارد البشرية داخل حدودها.' },
  },
  dha: {
    en: { url: 'https://www.dha.gov.ae/en',
      sentence: 'Clinics licensed in Dubai answer to the [Dubai Health Authority](URL) for how patient information is collected, stored and communicated.' },
    ar: { url: 'https://www.dha.gov.ae/ar',
      sentence: 'تخضع العيادات المرخّصة في دبي لـ[هيئة الصحة بدبي](URL) في طريقة جمع بيانات المرضى وتخزينها وتداولها.' },
  },
  doh: {
    en: { url: 'https://www.doh.gov.ae/en',
      sentence: 'In Abu Dhabi the equivalent regulator is the [Department of Health](URL), and its licensing conditions differ from Dubai\'s in the detail.' },
    ar: { url: 'https://www.doh.gov.ae/ar',
      sentence: 'وفي أبوظبي، الجهة المنظِّمة المقابلة هي [دائرة الصحة](URL)، وشروط الترخيص لديها تختلف عن دبي في التفاصيل.' },
  },
  dld: {
    en: { url: 'https://dubailand.gov.ae/en/',
      sentence: 'Every brokerage transaction in the emirate passes through the [Dubai Land Department](URL), which is also where the registration and listing rules come from.' },
    ar: { url: 'https://dubailand.gov.ae/ar/',
      sentence: 'تمر كل صفقة وساطة عقارية في الإمارة عبر [دائرة الأراضي والأملاك في دبي](URL)، وهي مصدر قواعد التسجيل والإعلان أيضاً.' },
  },
  dsc: {
    en: { url: 'https://www.dsc.gov.ae/en-us',
      sentence: 'Population and business-count figures for the emirate come from the [Dubai Statistics Center](URL) rather than from vendor market reports.' },
    ar: { url: 'https://www.dsc.gov.ae/ar-ae',
      sentence: 'تأتي أرقام السكان وعدد المنشآت في الإمارة من [مركز دبي للإحصاء](URL) لا من تقارير السوق الصادرة عن الموردين.' },
  },
  khda: {
    en: { url: 'https://web.khda.gov.ae/',
      sentence: 'Private schools and training institutes in Dubai are regulated by the [Knowledge and Human Development Authority](URL).' },
    ar: { url: 'https://web.khda.gov.ae/',
      sentence: 'تخضع المدارس الخاصة ومعاهد التدريب في دبي لـ[هيئة المعرفة والتنمية البشرية](URL).' },
  },
  fta: {
    en: { url: 'https://tax.gov.ae/en/',
      sentence: 'The [Federal Tax Authority](URL) sets the invoice content and record-keeping rules that any finance automation has to produce output against.' },
    ar: { url: 'https://tax.gov.ae/ar/',
      sentence: 'تحدد [الهيئة الاتحادية للضرائب](URL) قواعد محتوى الفواتير وحفظ السجلات التي يجب أن تلتزم بمخرجاتها أي أتمتة مالية.' },
  },
  ai2031: {
    en: { url: 'https://u.ae/en/about-the-uae/digital-uae/digital-technology/artificial-intelligence',
      sentence: 'The federal portal sets out the [national direction on artificial intelligence](URL), including the strategy that runs to 2031.' },
    ar: { url: 'https://u.ae/ar/about-the-uae/digital-uae/digital-technology/artificial-intelligence',
      sentence: 'تعرض البوابة الاتحادية [التوجه الوطني في الذكاء الاصطناعي](URL)، بما في ذلك الاستراتيجية الممتدة حتى عام 2031.' },
  },
  nist: {
    en: { url: 'https://www.nist.gov/itl/ai-risk-management-framework',
      sentence: 'The US National Institute of Standards and Technology organises its [AI Risk Management Framework](URL) around four functions: govern, map, measure and manage.' },
    ar: { url: 'https://www.nist.gov/itl/ai-risk-management-framework',
      sentence: 'ينظّم المعهد الوطني الأمريكي للمعايير والتقنية [إطار إدارة مخاطر الذكاء الاصطناعي](URL) حول أربع وظائف: الحوكمة والتوصيف والقياس والإدارة.' },
  },
  owasp: {
    en: { url: 'https://genai.owasp.org/llm-top-10/',
      sentence: "OWASP's [Top 10 for LLM Applications](URL) ranks prompt injection first among the risks specific to language-model software." },
    ar: { url: 'https://genai.owasp.org/llm-top-10/',
      sentence: 'تضع [قائمة OWASP لأخطر عشرة مخاطر في تطبيقات نماذج اللغة](URL) حقن التعليمات في المرتبة الأولى بين المخاطر الخاصة ببرمجيات النماذج اللغوية.' },
  },
  iso42001: {
    en: { url: 'https://www.iso.org/standard/81230.html',
      sentence: '[ISO/IEC 42001](URL) is the international management system standard for artificial intelligence, and it is the certification enterprise buyers in the region ask about most often.' },
    ar: { url: 'https://www.iso.org/standard/81230.html',
      sentence: 'المواصفة [ISO/IEC 42001](URL) هي المعيار الدولي لنظام إدارة الذكاء الاصطناعي، وهي الشهادة التي يسأل عنها المشترون المؤسسيون في المنطقة أكثر من غيرها.' },
  },
  iso27001: {
    en: { url: 'https://www.iso.org/standard/27001',
      sentence: 'For information security more broadly the reference standard is [ISO/IEC 27001](URL), which most UAE procurement checklists still lead with.' },
    ar: { url: 'https://www.iso.org/standard/27001',
      sentence: 'أما في أمن المعلومات عموماً فالمعيار المرجعي هو [ISO/IEC 27001](URL)، وهو ما تزال معظم قوائم المشتريات في الإمارات تبدأ به.' },
  },
  hai: {
    en: { url: 'https://hai.stanford.edu/ai-index/2025-ai-index-report',
      sentence: "Stanford's [AI Index report](URL) tracks adoption, cost and capability trends year on year, and is a useful check against vendor claims." },
    ar: { url: 'https://hai.stanford.edu/ai-index/2025-ai-index-report',
      sentence: 'يتابع [تقرير مؤشر الذكاء الاصطناعي من جامعة ستانفورد](URL) اتجاهات التبني والتكلفة والقدرات سنة بعد سنة، وهو مرجع مفيد لمراجعة ادعاءات الموردين.' },
  },
  rag: {
    en: { url: 'https://arxiv.org/abs/2005.11401',
      sentence: 'Retrieval-augmented generation was set out by Lewis and colleagues in [a 2020 paper](URL) that paired a language model with a separate document index.' },
    ar: { url: 'https://arxiv.org/abs/2005.11401',
      sentence: 'قدّم لويس وزملاؤه التوليد المعزَّز بالاسترجاع في [ورقة بحثية عام 2020](URL) تجمع نموذجاً لغوياً مع فهرس مستندات منفصل.' },
  },
  cot: {
    en: { url: 'https://arxiv.org/abs/2201.11903',
      sentence: 'Chain-of-thought prompting comes from [a 2022 paper by Wei and colleagues](URL), which showed that asking a model to work through intermediate steps improves multi-step reasoning.' },
    ar: { url: 'https://arxiv.org/abs/2201.11903',
      sentence: 'يعود أسلوب التفكير المتسلسل إلى [ورقة بحثية عام 2022 لوي وزملائه](URL)، أظهرت أن مطالبة النموذج بالمرور على خطوات وسيطة تحسّن الاستدلال متعدد الخطوات.' },
  },
  transformer: {
    en: { url: 'https://arxiv.org/abs/1706.03762',
      sentence: 'The architecture underneath all of these models was introduced in [the 2017 transformer paper](URL).' },
    ar: { url: 'https://arxiv.org/abs/1706.03762',
      sentence: 'قُدّمت البنية التي تقوم عليها هذه النماذج جميعاً في [ورقة المحوّلات عام 2017](URL).' },
  },
  nanda: {
    en: { url: 'https://nanda.media.mit.edu/ai_report_2025.pdf',
      sentence: "MIT's [Project NANDA report on the state of AI in business](URL) found that the large majority of enterprise GenAI pilots produced no measurable P&L impact." },
    ar: { url: 'https://nanda.media.mit.edu/ai_report_2025.pdf',
      sentence: 'خلص [تقرير Project NANDA الصادر عن MIT حول واقع الذكاء الاصطناعي في الأعمال](URL) إلى أن الغالبية العظمى من مشاريع الذكاء الاصطناعي التوليدي في المؤسسات لم تنتج أثراً مالياً قابلاً للقياس.' },
  },
  falcon: {
    en: { url: 'https://falconllm.tii.ae/',
      sentence: "Abu Dhabi's Technology Innovation Institute publishes the [Falcon family of open models](URL), several of which carry Arabic in the training mix." },
    ar: { url: 'https://falconllm.tii.ae/',
      sentence: 'ينشر معهد الابتكار التكنولوجي في أبوظبي [عائلة نماذج Falcon المفتوحة](URL)، وعدد منها مدرَّب على بيانات عربية.' },
  },
  mbzuai: {
    en: { url: 'https://mbzuai.ac.ae/',
      sentence: 'Arabic-language model research in the UAE is concentrated at [MBZUAI](URL) in Abu Dhabi.' },
    ar: { url: 'https://mbzuai.ac.ae/',
      sentence: 'تتركز أبحاث النماذج اللغوية العربية في الإمارات لدى [جامعة محمد بن زايد للذكاء الاصطناعي](URL) في أبوظبي.' },
  },
  oecd: {
    en: { url: 'https://oecd.ai/',
      sentence: 'The [OECD AI Policy Observatory](URL) tracks how different countries are regulating AI, which matters as soon as you operate in more than one market.' },
    ar: { url: 'https://oecd.ai/',
      sentence: 'يتابع [مرصد سياسات الذكاء الاصطناعي التابع لمنظمة التعاون الاقتصادي والتنمية](URL) كيفية تنظيم الدول المختلفة للذكاء الاصطناعي، وهو ما يهم فور العمل في أكثر من سوق.' },
  },
  itu: {
    en: { url: 'https://www.itu.int/en/Pages/default.aspx',
      sentence: 'The [International Telecommunication Union](URL) publishes the connectivity statistics that most regional benchmarks are built on.' },
    ar: { url: 'https://www.itu.int/en/Pages/default.aspx',
      sentence: 'ينشر [الاتحاد الدولي للاتصالات](URL) إحصاءات الاتصال التي تُبنى عليها معظم المقارنات الإقليمية.' },
  },
  verizon: {
    en: { url: 'https://www.verizon.com/business/resources/reports/dbir/',
      sentence: "Verizon's annual [Data Breach Investigations Report](URL) is the standard reference for how breaches actually begin." },
    ar: { url: 'https://www.verizon.com/business/resources/reports/dbir/',
      sentence: 'يُعد [تقرير Verizon السنوي للتحقيق في اختراقات البيانات](URL) المرجع القياسي لكيفية بدء الاختراقات فعلياً.' },
  },
  msdiffusion: {
    en: { url: 'https://blogs.microsoft.com/on-the-issues/2026/05/07/the-state-of-global-ai-diffusion-in-2026/',
      sentence: "Microsoft's [analysis of global AI diffusion](URL) is where the frequently quoted UAE workplace-adoption figures come from." },
    ar: { url: 'https://blogs.microsoft.com/on-the-issues/2026/05/07/the-state-of-global-ai-diffusion-in-2026/',
      sentence: 'تعود أرقام تبني الذكاء الاصطناعي في مكان العمل بالإمارات، وهي الأكثر تداولاً، إلى [تحليل مايكروسوفت لانتشار الذكاء الاصطناعي عالمياً](URL).' },
  },
  deloitte: {
    en: { url: 'https://www.deloitte.com/middle-east/en.html',
      sentence: '[Deloitte Middle East](URL) publishes regional research on how AI adoption is actually landing across GCC sectors.' },
    ar: { url: 'https://www.deloitte.com/middle-east/en.html',
      sentence: 'تنشر [ديلويت الشرق الأوسط](URL) أبحاثاً إقليمية عن واقع تبني الذكاء الاصطناعي في قطاعات دول الخليج.' },
  },
  pwc: {
    en: { url: 'https://www.pwc.com/m1/en.html',
      sentence: '[PwC Middle East](URL) publishes comparable regional work, and reading both is a cheap way to spot where a single number is being over-quoted.' },
    ar: { url: 'https://www.pwc.com/m1/en.html',
      sentence: 'وتنشر [بي دبليو سي الشرق الأوسط](URL) أعمالاً إقليمية مماثلة، وقراءة المصدرين معاً طريقة سهلة لاكتشاف الأرقام المتداولة أكثر مما تستحق.' },
  },
  pew: {
    en: { url: 'https://www.pewresearch.org/',
      sentence: '[Pew Research](URL) publishes public-attitude surveys on AI that are worth reading before you decide how much to disclose to customers.' },
    ar: { url: 'https://www.pewresearch.org/',
      sentence: 'ينشر [مركز بيو للأبحاث](URL) استطلاعات عن مواقف الجمهور من الذكاء الاصطناعي تستحق القراءة قبل تحديد حجم الإفصاح للعملاء.' },
  },
  who: {
    en: { url: 'https://www.who.int/publications/i/item/9789240029200',
      sentence: 'The World Health Organization has published [guidance on ethics and governance of AI for health](URL) that clinical deployments are measured against.' },
    ar: { url: 'https://www.who.int/publications/i/item/9789240029200',
      sentence: 'أصدرت منظمة الصحة العالمية [إرشادات حول أخلاقيات وحوكمة الذكاء الاصطناعي في الصحة](URL) تُقاس عليها التطبيقات السريرية.' },
  },
};
